services:
  asentrx_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asentrx_container
    restart: unless-stopped
    env_file:
      - .env-prod
    volumes:
      - ./app_logs:/app/logs
